Fix build directions with `make`
When following the current directions to build `stanc3` with `make`, I get the error:
```+ install_missing='t know how to build scripts/src/stanc/stanc.exe'
+ echo 'Trying to install missing deps for stanc with t know how to build scripts/src/stanc/stanc.exe'
Trying to install missing deps for stanc with t know how to build scripts/src/stanc/stanc.exe
+ t know how to build scripts/src/stanc/stanc.exe
setup_dev_env.sh: line 15: t: command not found
```
This looks like `bash` attempting to parse the output of `dune external-lib-deps --missing src/stanc/stanc.exe`, which gives:
```Entering directory '/Users/chrislambda/stanc3'
Error: Don't know how to build scripts/src/stanc/stanc.exe```

The error seems to be due to the fact that `scripts/src/stanc` doesn't exist; if the setup script is run from the toplevel, everything builds fine with no error:
```bash -x scripts/setup_dev_env.sh```